export default {
    THEME_CHANGE:'THEME_CHANGE',
    THEME_INIT:'THEME_INIT',
    HOME_REFRESH:'HOME_REFRESH',
    LOAD_HOME_FAIL:'LOAD_HOME_FAIL',
    LOAD_HOME_SUCCESS:'LOAD_HOME_SUCCESS',
    LOAD_HOME_MORE_SUCCESS:'LOAD_HOME_MORE_SUCCESS',
    LOAD_HOME_MORE_FAIL:'LOAD_HOME_MORE_FAIL'
}